/* Kartoonia — content catalog
   Original kids' cartoon shows & movies (invented, non-copyrighted), bilingual EN/AR.
   Each title carries a 2-color gradient + a soft motif color used to render
   designed placeholder poster art (no fake character drawings).
   type: "series" (TV show, has seasons/episodes) | "movie" (single film). */

window.STRINGS = {
  en: {
    appName: "Kartoonia",
    brandA: "Kartoon", brandB: "ia",
    nav_search: "Search",
    nav_home: "Home",
    nav_tv: "TV Shows",
    nav_movies: "Movies",
    nav_mylist: "My List",
    settings: "Settings",
    row_continue: "Keep Watching",
    row_popular: "Popular Now",
    row_new: "New Episodes",
    row_adventure: "Adventure Time",
    row_learn: "Learn & Play",
    row_bedtime: "Bedtime Calm",
    row_movies: "Movie Night",
    play: "Play",
    resume: "Resume",
    moreInfo: "More Info",
    myList: "My List",
    addList: "Add to List",
    inList: "In My List",
    episodes: "Episodes",
    season: "Season",
    searchPlaceholder: "Search shows and movies",
    resultsFor: "Results",
    noResults: "No titles found",
    startTyping: "Start typing to search",
    profile: "Hi, Salma",
    clear: "Clear",
    space: "Space",
    watchNow: "Watch Now",
    featured: "FEATURED",
    minutes: "min",
    movie: "Movie",
    series: "Series",
    backHint: "Back",
    okHint: "Select",
    remoteTitle: "Remote",
    epShort: "E",
    seasonShort: "S",
    left: "left",
    voice: "Voice",
    voiceListening: "Listening…",
    voiceSpeak: "Say the name of a show or movie",
    voiceTryAgain: "Tap the mic and speak",
    kbLatin: "EN",
    kbArabic: "AR",
    kbHint: "Keyboard",
    alpha_all: "All",
    cat_new: "Newly Released",
    cat_adventure: "Adventure",
    cat_action: "Action & Heroes",
    cat_comedy: "Comedy & Fun",
    cat_fantasy: "Fantasy & Sci-Fi",
    cat_preschool: "Preschool Picks",
    cat_bedtime: "Wind-Down & Bedtime",
    cat_classics: "Timeless Classics",
    topten: "Top 10 Today",
    spotlight: "In the Spotlight",
    trailer: "Trailer",
    server: "Server",
    servers: "Servers",
    chooseServer: "Choose a server",
    quality: "Quality",
    nowPlaying: "Now playing on",
    closeTrailer: "Close",
    filter_all: "All",
    filter_tv: "TV Shows",
    filter_movies: "Movies",
    filter_preschool: "Preschool",
    filter_bigkids: "Big Kids",
    filters: "Filters",
    set_language: "Language",
    set_lang_en: "English",
    set_lang_ar: "العربية",
    set_motion: "Reduce Motion",
    set_autoplay: "Autoplay Previews",
    set_subtitles: "Always Show Subtitles",
    on: "On",
    off: "Off",
    set_hint: "Choose your language and playback preferences",
    mylist_empty: "Your list is empty. Add shows with the + button.",
    browse_tv: "TV Shows",
    browse_movies: "Movies",
    browse_mylist: "My List",
  },
  ar: {
    appName: "كرتونيا",
    brandA: "كرتون", brandB: "يا",
    nav_search: "بحث",
    nav_home: "الرئيسية",
    nav_tv: "مسلسلات",
    nav_movies: "أفلام",
    nav_mylist: "قائمتي",
    settings: "الإعدادات",
    row_continue: "تابع المشاهدة",
    row_popular: "الأكثر مشاهدة",
    row_new: "حلقات جديدة",
    row_adventure: "وقت المغامرة",
    row_learn: "تعلّم والعب",
    row_bedtime: "هدوء ما قبل النوم",
    row_movies: "ليلة الأفلام",
    play: "تشغيل",
    resume: "متابعة",
    moreInfo: "المزيد",
    myList: "قائمتي",
    addList: "أضف إلى قائمتي",
    inList: "في قائمتي",
    episodes: "الحلقات",
    season: "الموسم",
    searchPlaceholder: "ابحث عن المسلسلات والأفلام",
    resultsFor: "النتائج",
    noResults: "لا توجد نتائج",
    startTyping: "ابدأ الكتابة للبحث",
    profile: "أهلاً سلمى",
    clear: "مسح",
    space: "مسافة",
    watchNow: "شاهد الآن",
    featured: "مميّز",
    minutes: "د",
    movie: "فيلم",
    series: "مسلسل",
    backHint: "رجوع",
    okHint: "اختيار",
    remoteTitle: "جهاز التحكم",
    epShort: "ح",
    seasonShort: "م",
    left: "متبقٍ",
    voice: "صوت",
    voiceListening: "جارٍ الاستماع…",
    voiceSpeak: "قل اسم مسلسل أو فيلم",
    voiceTryAgain: "اضغط الميكروفون وتحدّث",
    kbLatin: "EN",
    kbArabic: "AR",
    kbHint: "لوحة المفاتيح",
    alpha_all: "الكل",
    cat_new: "صدر حديثاً",
    cat_adventure: "مغامرة",
    cat_action: "أكشن وأبطال",
    cat_comedy: "كوميديا ومرح",
    cat_fantasy: "خيال وعلوم",
    cat_preschool: "اختيارات ما قبل المدرسة",
    cat_bedtime: "الاسترخاء وما قبل النوم",
    cat_classics: "كلاسيكيات خالدة",
    topten: "الأكثر مشاهدة اليوم",
    spotlight: "تحت الأضواء",
    trailer: "المقطع الدعائي",
    server: "خادم",
    servers: "الخوادم",
    chooseServer: "اختر الخادم",
    quality: "الجودة",
    nowPlaying: "يعرض الآن عبر",
    closeTrailer: "إغلاق",
    filter_all: "الكل",
    filter_tv: "مسلسلات",
    filter_movies: "أفلام",
    filter_preschool: "ما قبل المدرسة",
    filter_bigkids: "الأطفال الكبار",
    filters: "تصفية",
    set_language: "اللغة",
    set_lang_en: "English",
    set_lang_ar: "العربية",
    set_motion: "تقليل الحركة",
    set_autoplay: "تشغيل المعاينات تلقائياً",
    set_subtitles: "إظهار الترجمة دائماً",
    on: "تشغيل",
    off: "إيقاف",
    set_hint: "اختر اللغة وتفضيلات التشغيل",
    mylist_empty: "قائمتك فارغة. أضف المسلسلات بزر +.",
    browse_tv: "المسلسلات",
    browse_movies: "الأفلام",
    browse_mylist: "قائمتي",
  },
};

window.CATALOG = [
  {
    id: "falcon", type: "series",
    en: "Captain Falcon", ar: "الكابتن صقر",
    g1: "#FF7A3D", g2: "#C9263E", motif: "#FFD56B",
    age: 7, year: 2025, mins: 24, seasons: 3, episodes: 18,
    genreEn: "Adventure · Action", genreAr: "مغامرة · أكشن",
    synEn: "A fearless young pilot and his desert falcon defend the floating city of Suhail from sky-pirates — one daring rescue at a time.",
    synAr: "طيّار شاب لا يعرف الخوف وصقره الصحراوي يدافعان عن مدينة سهيل الطائرة ضد قراصنة السماء، في مغامرة إنقاذ تلو الأخرى.",
    rows: ["popular", "adventure", "new"], progress: 0.42, hero: true,
  },
  {
    id: "lulu", type: "series",
    en: "Lulu & Dodo", ar: "لولو ودودو",
    g1: "#FF6FB5", g2: "#7A3DF5", motif: "#FFE08A",
    age: 3, year: 2026, mins: 11, seasons: 2, episodes: 40,
    genreEn: "Comedy · Preschool", genreAr: "كوميديا · ما قبل المدرسة",
    synEn: "Best friends Lulu the fennec and Dodo the dove turn every ordinary day in the oasis into a giggly little adventure.",
    synAr: "الصديقان لولو الفنك ودودو الحمامة يحوّلان كل يوم عادي في الواحة إلى مغامرة صغيرة مليئة بالضحك.",
    rows: ["continue", "popular", "bedtime"], progress: 0.7,
  },
  {
    id: "robo", type: "series",
    en: "Robo Friends", ar: "أصدقاء الروبوت",
    g1: "#28C7C7", g2: "#1B5BD8", motif: "#BFFCF0",
    age: 6, year: 2025, mins: 22, seasons: 2, episodes: 24,
    genreEn: "Sci-Fi · Friendship", genreAr: "خيال علمي · صداقة",
    synEn: "Three mismatched robots wake up in a quiet workshop and learn what it really means to be a friend.",
    synAr: "ثلاثة روبوتات مختلفة تستيقظ في ورشة هادئة لتتعلّم معنى الصداقة الحقيقية.",
    rows: ["continue", "popular", "learn"], progress: 0.18,
  },
  {
    id: "desert", type: "series",
    en: "Desert Adventures", ar: "مغامرات الصحراء",
    g1: "#F6B23C", g2: "#E0552B", motif: "#FFE8A3",
    age: 6, year: 2024, mins: 20, seasons: 4, episodes: 32,
    genreEn: "Adventure · Nature", genreAr: "مغامرة · طبيعة",
    synEn: "Twins Nour and Faris ride their camel across golden dunes, uncovering the secrets and creatures of the great desert.",
    synAr: "التوأمان نور وفارس يجوبان الكثبان الذهبية على ظهر جملهما لاكتشاف أسرار الصحراء الكبرى ومخلوقاتها.",
    rows: ["popular", "adventure", "new"], progress: 0,
  },
  {
    id: "space", type: "series",
    en: "Space Cats", ar: "قطط الفضاء",
    g1: "#7A5CFF", g2: "#241B6B", motif: "#9BE8FF",
    age: 7, year: 2026, mins: 23, seasons: 1, episodes: 12,
    genreEn: "Sci-Fi · Comedy", genreAr: "خيال علمي · كوميديا",
    synEn: "A crew of curious cats pilots a saucer-shaped ship through the galaxy, chasing the legendary Yarn of the Stars.",
    synAr: "طاقم من القطط الفضولية يقود سفينة على شكل صحن عبر المجرة بحثاً عن كرة الصوف النجمية الأسطورية.",
    rows: ["new", "adventure", "popular"], progress: 0,
  },
  {
    id: "chef", type: "series",
    en: "The Tiny Chef", ar: "الطبّاخ الصغير",
    g1: "#FF9E4A", g2: "#D63B6E", motif: "#FFE6B0",
    age: 4, year: 2025, mins: 12, seasons: 3, episodes: 36,
    genreEn: "Comedy · Cooking", genreAr: "كوميديا · طبخ",
    synEn: "In a kitchen full of friendly veggies, little chef Maya cooks up colorful recipes and even bigger surprises.",
    synAr: "في مطبخ مليء بالخضار اللطيفة، تطبخ الطاهية الصغيرة مايا وصفات ملوّنة ومفاجآت أكبر.",
    rows: ["continue", "learn", "popular"], progress: 0.55,
  },
  {
    id: "garden", type: "series",
    en: "Magic Garden", ar: "الحديقة السحرية",
    g1: "#3DD17F", g2: "#127A5A", motif: "#D6FFB0",
    age: 3, year: 2024, mins: 11, seasons: 2, episodes: 28,
    genreEn: "Fantasy · Preschool", genreAr: "خيال · ما قبل المدرسة",
    synEn: "Behind a tiny green door, every flower can talk and every puddle hides a wonder waiting to be discovered.",
    synAr: "خلف باب أخضر صغير، تتكلّم كل زهرة وتخبئ كل بركة عجيبة تنتظر من يكتشفها.",
    rows: ["learn", "bedtime", "popular"], progress: 0,
  },
  {
    id: "dino", type: "series",
    en: "Dino Squad", ar: "فريق الديناصورات",
    g1: "#5FCB46", g2: "#1F6F3A", motif: "#EAFFA8",
    age: 6, year: 2025, mins: 22, seasons: 2, episodes: 20,
    genreEn: "Adventure · Comedy", genreAr: "مغامرة · كوميديا",
    synEn: "Four friendly dinosaurs use teamwork — and a lot of stomping — to keep their prehistoric valley safe and silly.",
    synAr: "أربعة ديناصورات لطيفة تستخدم روح الفريق — وكثيراً من الدبدبة — لحماية واديها القديم بمرح.",
    rows: ["popular", "adventure", "new"], progress: 0,
  },
  {
    id: "ocean", type: "series",
    en: "Ocean Tales", ar: "حكايات المحيط",
    g1: "#2FB7E8", g2: "#114E9E", motif: "#BDF3FF",
    age: 4, year: 2024, mins: 14, seasons: 3, episodes: 30,
    genreEn: "Adventure · Nature", genreAr: "مغامرة · طبيعة",
    synEn: "Dive with Salma the sea-turtle through coral cities and gentle tides, where every current tells a story.",
    synAr: "اغطس مع سلمى السلحفاة البحرية عبر مدن المرجان والأمواج الهادئة، حيث يروي كل تيّار حكاية.",
    rows: ["bedtime", "learn", "popular"], progress: 0,
  },
  {
    id: "salma", type: "series",
    en: "Super Salma", ar: "سوبر سلمى",
    g1: "#FF4D6D", g2: "#8E1A6B", motif: "#FFD0E0",
    age: 7, year: 2026, mins: 23, seasons: 1, episodes: 10,
    genreEn: "Action · Superhero", genreAr: "أكشن · أبطال خارقون",
    synEn: "By day she's an ordinary schoolgirl; by night, Super Salma uses cleverness and kindness to save her city.",
    synAr: "في النهار تلميذة عادية، وفي الليل تتحوّل سوبر سلمى لتنقذ مدينتها بالذكاء والطيبة.",
    rows: ["new", "popular", "adventure"], progress: 0,
  },
  {
    id: "layla", type: "series",
    en: "Brave Layla", ar: "ليلى الشجاعة",
    g1: "#F26B5E", g2: "#7A1F3D", motif: "#FFD9A8",
    age: 6, year: 2025, mins: 21, seasons: 2, episodes: 16,
    genreEn: "Fantasy · Adventure", genreAr: "خيال · مغامرة",
    synEn: "Armed with her grandmother's lantern and a heart full of courage, Layla journeys through tales as old as the moon.",
    synAr: "بفانوس جدتها وقلب مليء بالشجاعة، تنطلق ليلى في رحلة عبر حكايات قديمة قِدم القمر.",
    rows: ["continue", "adventure", "bedtime"], progress: 0.3,
  },
  {
    id: "cloud", type: "series",
    en: "Sleepy Cloud", ar: "الغيمة النعسانة",
    g1: "#8FA8FF", g2: "#3A3F8F", motif: "#E5ECFF",
    age: 2, year: 2024, mins: 8, seasons: 4, episodes: 48,
    genreEn: "Bedtime · Preschool", genreAr: "ما قبل النوم · ما قبل المدرسة",
    synEn: "A soft little cloud drifts over sleeping towns, sprinkling gentle dreams and the quietest of lullabies.",
    synAr: "غيمة صغيرة ناعمة تنساب فوق المدن النائمة، تنثر الأحلام اللطيفة وأهدأ التهويدات.",
    rows: ["bedtime", "learn"], progress: 0,
  },

  /* ---------- MOVIES ---------- */
  {
    id: "lantern", type: "movie",
    en: "The Lantern Festival", ar: "مهرجان الفوانيس",
    g1: "#FFB23C", g2: "#B5267A", motif: "#FFE59E",
    age: 5, year: 2026, mins: 84, seasons: 0, episodes: 0,
    genreEn: "Musical · Family", genreAr: "موسيقي · عائلي",
    synEn: "On the night of the great festival, a shy girl must light the oldest lantern in the city before the last star fades.",
    synAr: "في ليلة المهرجان الكبير، على فتاة خجولة أن تُضيء أقدم فانوس في المدينة قبل أن يخبو آخر نجم.",
    rows: ["movies", "popular", "new"], progress: 0,
  },
  {
    id: "skypirates", type: "movie",
    en: "Falcon: Sky Pirates", ar: "صقر: قراصنة السماء",
    g1: "#FF7A3D", g2: "#5B1530", motif: "#FFD56B",
    age: 7, year: 2025, mins: 92, seasons: 0, episodes: 0,
    genreEn: "Adventure · Action", genreAr: "مغامرة · أكشن",
    synEn: "Captain Falcon's biggest adventure yet takes to the open skies in a feature-length race against the Pirate King.",
    synAr: "أكبر مغامرات الكابتن صقر تنطلق في سماء مفتوحة في سباق طويل ضد ملك القراصنة.",
    rows: ["movies", "adventure", "popular"], progress: 0.12,
  },
  {
    id: "luluday", type: "movie",
    en: "Lulu's Big Day", ar: "يوم لولو الكبير",
    g1: "#FF6FB5", g2: "#4B2A9E", motif: "#FFE08A",
    age: 3, year: 2026, mins: 72, seasons: 0, episodes: 0,
    genreEn: "Comedy · Family", genreAr: "كوميديا · عائلي",
    synEn: "It's the oasis fair, and Lulu and Dodo have one wobbly, wonderful day to win the golden balloon.",
    synAr: "إنه يوم معرض الواحة، وأمام لولو ودودو يومٌ واحد رائع ومضحك للفوز بالبالون الذهبي.",
    rows: ["movies", "bedtime", "popular"], progress: 0,
  },
  {
    id: "roborescue", type: "movie",
    en: "Robo Rescue", ar: "إنقاذ الروبوت",
    g1: "#28C7C7", g2: "#14306B", motif: "#BFFCF0",
    age: 6, year: 2025, mins: 88, seasons: 0, episodes: 0,
    genreEn: "Sci-Fi · Adventure", genreAr: "خيال علمي · مغامرة",
    synEn: "When the workshop loses power, three little robots set off across the city on a movie-sized mission to bring the lights back.",
    synAr: "عندما تنقطع الطاقة عن الورشة، تنطلق ثلاثة روبوتات صغيرة عبر المدينة في مهمة بحجم فيلم لإعادة الأضواء.",
    rows: ["movies", "learn", "new"], progress: 0,
  },
  {
    id: "moonboat", type: "movie",
    en: "The Moon Boat", ar: "قارب القمر",
    g1: "#8FA8FF", g2: "#2A2F7A", motif: "#E5ECFF",
    age: 4, year: 2024, mins: 76, seasons: 0, episodes: 0,
    genreEn: "Bedtime · Fantasy", genreAr: "ما قبل النوم · خيال",
    synEn: "Every sleepy child is invited aboard the Moon Boat for one calm voyage across a sea of soft, glowing dreams.",
    synAr: "كل طفل نعسان مدعوّ إلى قارب القمر لرحلة هادئة عبر بحر من الأحلام الناعمة المتوهجة.",
    rows: ["movies", "bedtime"], progress: 0,
  },
];

// sanitize motif colors
window.CATALOG.forEach(s => { if (!/^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(s.motif)) s.motif = "#CFFFF0"; });
